### ISSUE TITLE
Add remaining I/O registers of ATmega8A to avrsim/include/mcusim/avr/sim/vcd_regs.h

### ISSUE THREAD

**Issue by dsalychev** [dsalychev/mcusim#8]
It's required to make all missing I/O registers of ATmega8A microcontroller available to include into VCD dump.

You'll have to scan through datasheet http://www.atmel.com/Images/Atmel-8159-8-bit-AVR-microcontroller-ATmega8A_datasheet.pdf (page 380, 381), copy name of a register (MCUCSR for instance), try to find it in [avrsim/include/mcusim/avr/sim/vcd_regs.h](https://github.com/dsalychev/mcusim/blob/master/avrsim/include/mcusim/avr/sim/vcd_regs.h) and add lines like this
- https://github.com/dsalychev/mcusim/blob/master/avrsim/include/mcusim/avr/sim/vcd_regs.h#L242-L244
and this
- https://github.com/dsalychev/mcusim/blob/master/avrsim/include/mcusim/avr/sim/vcd_regs.h#L322

You may build and run `avrsim` as follows to print a list of registers available for VCD dump file:
`./avrsim -p m8a -U flash:w:dhtc.txt --dump-regs=?`
You'll see a new register in a list if you perform these steps described above correctly.

Please, feel free to ask me in case of any trouble or help required.

[dhtc.txt](https://github.com/dsalychev/mcusim/files/1548776/dhtc.txt)

**Comment by dsalychev** [comment]
I'd like to notify you that I accept patches shared here or via [mcusim-dev](https://groups.google.com/forum/#!forum/mcusim-dev) mailing list.

_Please, do not send pull request via GitHub._

**Comment by asalychev** [comment]
[0001-ATMega8A-I-O-VCD.patch.txt](https://github.com/dsalychev/mcusim/files/1587518/0001-ATMega8A-I-O-VCD.patch.txt)

**Comment by asalychev** [comment]
[0001-Additional-names-of-registers-are-brought-in-a-VCD-f.patch.txt](https://github.com/dsalychev/mcusim/files/1589142/0001-Additional-names-of-registers-are-brought-in-a-VCD-f.patch.txt)

**Comment by asalychev** [comment]
[0001-Names-of-registers-for-ATmega328-328p-in-VCD-a-file-.patch.txt](https://github.com/dsalychev/mcusim/files/1590615/0001-Names-of-registers-for-ATmega328-328p-in-VCD-a-file-.patch.txt)

**Comment by dsalychev** [comment]
The last patch seems correct, but there is one redundant register which doesn't seem to exist (it's rather a bit in a register): `SPDR0`. Many AVRs have a register called `SPDR` and this one is already in `vcd_regs.h`.

`SPDR0` can be defined in `ioXXX.h` headers as a bit position in the register, i.e. it's 0 for ATmega328p, so problem is in incorrect address of this fake register:
```
$ ./avrsim -p m328p -U flash:w:dhtc.hex --dump-regs=? | grep SPDR
INFO: SPDR (0x4E)
INFO: SPDR0 (0x 0)
```
It can be removed at all, I think.

**Comment by asalychev** [comment]
[0001-Names-of-registers-for-ATmega-328-328p-have-been-add.patch.txt](https://github.com/dsalychev/mcusim/files/1591453/0001-Names-of-registers-for-ATmega-328-328p-have-been-add.patch.txt)

**Comment by dsalychev** [comment]
Well, even more work has been done. There are I/O registers for ATmega8A, ATmega328/ATmega328P and ATmega2560 added by the patches.

@asalychev, good job 👍 
I'm going to close this issue.
